[package]
name = "xrf-error-derive"
version = "0.1.0"
publish = false
edition.workspace = true
rust-version.workspace = true

[lib]
proc-macro = true

[dependencies]
convert_case = "0.11.0"
proc-macro2 = "1.0.107"
quote = "1.0.47"
syn = "3.0.3"

[dev-dependencies]
trybuild = "1.0"

[lints]
workspace = true
