//! What the characters and reserved names in an LTX file mean, shared by everything that reads or writes one.

pub(crate) mod ltx_syntax;

pub use crate::syntax::ltx_syntax::{
  DEFAULT_KV_SEPARATOR, LTX_EXTENSION, LTX_LINE_SEPARATOR, LTX_SCHEME_EXTENSION, LTX_SCHEME_FIELD,
  LTX_SCHEME_LTX_FILENAME, LTX_SCHEME_STRICT_FIELD, LTX_SYMBOL_ANY, LTX_SYMBOL_ARRAY, LTX_SYMBOL_COMMENT,
  LTX_SYMBOL_INCLUDE, LTX_SYMBOL_INHERIT, LTX_SYMBOL_OPTIONAL, LTX_SYMBOL_SCHEME, LTX_SYMBOL_SECTION_CLOSE,
  LTX_SYMBOL_SECTION_OPEN, ROOT_SECTION, SYSTEM_LTX_FILENAME, VIRTUAL_LTX_PATH,
};
