[package]
name = "xrf-xml"
version = "0.1.0"
publish = false
edition.workspace = true
rust-version.workspace = true

[dependencies]
quick-xml = { version = "0.41.0", features = ["serialize", "serde"] }
roxmltree = "0.21.1"
serde = { workspace = true }
xrf-error = { workspace = true }
xrf-utils = { workspace = true }

[lints]
workspace = true
