[package]
name = "xrf-material"
version = "0.1.0"
publish = false
edition.workspace = true
rust-version.workspace = true

[lib]
path = "src/lib.rs"

[dependencies]
serde = { workspace = true }
specta = { workspace = true, optional = true }
xrf-chunk = { workspace = true }
xrf-db = { workspace = true }
xrf-error = { workspace = true }
xrf-test-utils = { workspace = true, optional = true }
xrf-vfs = { workspace = true }

[dev-dependencies]
xrf-db = { workspace = true, features = ["fixtures"] }
xrf-test-utils = { workspace = true }

[features]
typescript-bindings = ["specta", "xrf-vfs/typescript-bindings"]
fixtures = ["xrf-test-utils", "xrf-db/fixtures"]

[lints]
workspace = true
