[package]
name = "xrf-renderer-core"
version = "0.1.0"
publish = false
edition.workspace = true
rust-version.workspace = true

[dependencies]
bytemuck = { workspace = true }
log = { workspace = true }
offset-allocator = { workspace = true }
serde = { workspace = true }
wgpu = { workspace = true }
xrf-error = { workspace = true }

[dev-dependencies]
pollster = { workspace = true }
serde_json = { workspace = true }

[lints]
workspace = true
