use derive_more::Display;

/// Stable rule identifiers assigned to gamedata verification findings.
#[derive(Clone, Copy, Debug, Display, Eq, Hash, Ord, PartialEq, PartialOrd)]
#[non_exhaustive]
pub enum GamedataVerificationRule {
  #[display("animations.hud-item")]
  AnimationsHudItem,
  #[display("animations.motion-collision")]
  AnimationsMotionCollision,
  #[display("animations.player-hud")]
  AnimationsPlayerHud,
  #[display("checks.execution")]
  CheckExecution,
  #[display("levels.ai-guid")]
  LevelsAiGuid,
  #[display("levels.ai-node-count")]
  LevelsAiNodeCount,
  #[display("levels.ai-version")]
  LevelsAiVersion,
  #[display("levels.cform-version")]
  LevelsCformVersion,
  #[display("levels.details-pair")]
  LevelsDetailsPair,
  #[display("levels.file-empty")]
  LevelsFileEmpty,
  #[display("levels.file-truncated")]
  LevelsFileTruncated,
  #[display("levels.graph-duplicate")]
  LevelsGraphDuplicate,
  #[display("levels.graph-guid")]
  LevelsGraphGuid,
  #[display("levels.header-version")]
  LevelsHeaderVersion,
  #[display("levels.level-guid")]
  LevelsLevelGuid,
  #[display("levels.ltx-read")]
  LevelsLtxRead,
  #[display("levels.map-texture")]
  LevelsMapTexture,
  #[display("levels.missing-bundle")]
  LevelsMissingBundle,
  #[display("levels.missing-file")]
  LevelsMissingFile,
  #[display("levels.orphan-bundle")]
  LevelsOrphanBundle,
  #[display("levels.roster-conflict")]
  LevelsRosterConflict,
  #[display("levels.shader-reference")]
  LevelsShaderReference,
  #[display("levels.shaders-chunk")]
  LevelsShadersChunk,
  #[display("levels.texture-reference")]
  LevelsTextureReference,
  #[display("levels.undeclared-map")]
  LevelsUndeclaredMap,
  #[display("ltx.formatting")]
  LtxFormatting,
  #[display("ltx.schema")]
  LtxSchema,
  #[display("ltx.verification")]
  LtxVerification,
  #[display("meshes.chunk-residue")]
  MeshesChunkResidue,
  #[display("meshes.motion-label")]
  MeshesMotionLabel,
  #[display("meshes.motion-read")]
  MeshesMotionRead,
  #[display("meshes.motion-validation")]
  MeshesMotionValidation,
  #[display("meshes.path")]
  MeshesPath,
  #[display("meshes.read")]
  MeshesRead,
  #[display("meshes.shader-library")]
  MeshesShaderLibrary,
  #[display("meshes.validation")]
  MeshesValidation,
  #[display("particles.library")]
  ParticlesLibrary,
  #[display("particles.texture")]
  ParticlesTexture,
  #[display("particles-usage.reference")]
  ParticlesUsageReference,
  #[display("particles-usage.spawn")]
  ParticlesUsageSpawn,
  #[display("particles-usage.spawn-custom-data")]
  ParticlesUsageSpawnCustomData,
  #[display("scripts.path")]
  ScriptsPath,
  #[display("scripts.read")]
  ScriptsRead,
  #[display("scripts.syntax")]
  ScriptsSyntax,
  #[display("shaders.include-cycle")]
  ShadersIncludeCycle,
  #[display("shaders.include-missing")]
  ShadersIncludeMissing,
  #[display("shaders.include-syntax")]
  ShadersIncludeSyntax,
  #[display("shaders.lua-syntax")]
  ShadersLuaSyntax,
  #[display("shaders.renderer-root")]
  ShadersRendererRoot,
  #[display("shaders.source-invalid")]
  ShadersSourceInvalid,
  #[display("shaders.source-read")]
  ShadersSourceRead,
  #[display("sounds.files")]
  SoundsFiles,
  #[display("sounds.references")]
  SoundsReferences,
  #[display("spawns.path")]
  SpawnsPath,
  #[display("spawns.read")]
  SpawnsRead,
  #[display("textures.bump")]
  TexturesBump,
  #[display("textures.path")]
  TexturesPath,
  #[display("textures.read")]
  TexturesRead,
  #[display("textures.dds")]
  TexturesValidation,
  #[display("weapons.validation")]
  WeaponsValidation,
  #[display("weathers.definitions")]
  WeathersDefinitions,
  #[display("weathers.files")]
  WeathersFiles,
  #[display("weathers.validation")]
  WeathersValidation,
}

#[cfg(test)]
mod tests {
  use super::GamedataVerificationRule;

  #[test]
  fn displays_stable_rule_ids() {
    assert_eq!(
      GamedataVerificationRule::ParticlesUsageSpawnCustomData.to_string(),
      "particles-usage.spawn-custom-data"
    );
    assert_eq!(
      GamedataVerificationRule::ShadersIncludeMissing.to_string(),
      "shaders.include-missing"
    );
  }
}
