[package]
name = "xrf-sound"
version = "0.1.0"
publish = false
edition = "2024"
rust-version.workspace = true

[dependencies]
ogg = "0.9.2"
symphonia = { version = "0.6.0", default-features = false, features = ["vorbis"] }
xrf-error = { workspace = true }
xrf-utils = { workspace = true }

[lints]
workspace = true
